CREATE or REPLACE SCHEMA MYTESTDB;
CREATE OR REPLACE TABLE HELLO_WORLD
(
   FIRST_NAME VARCHAR
  ,LAST_NAME VARCHAR
  ,LAST_UPDATE_DATE DATE
);

CREATE OR REPLACE TABLE STUDENT
(
  STUDENT_ID VARCHAR(100)
  ,STUDENT_FIRST_NAME VARCHAR(100)
  ,STUDENT_LAST_NAME VARCHAR(100)
);

