name: Deploy to Staging

on:
  push:
    branches:
      - staging
    paths:
      - 'dbscripts/**'

  workflow_dispatch:

jobs:
  deploy-snowflake-changes-job:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Snowflake
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE: 'StagingDB'
        run: |
          echo "Using pre-installed SnowSQL to deploy to staging"
          "C:\\Program Files\\Snowflake SnowSQL\\snowsql.exe" -a $SNOWFLAKE_ACCOUNT -u $SNOWFLAKE_USER -p $SNOWFLAKE_PASSWORD -r $SNOWFLAKE_ROLE -w $SNOWFLAKE_WAREHOUSE -d $SNOWFLAKE_DATABASE -f $GITHUB_WORKSPACE/dbscripts/your_script.sql
      shell: cmd
